version: "3.3"

services:
  json_server:
      container_name: json-server-container
      image: json-server-image
      build:
        context: .
      ports:
        - 9200:3000
      volumes:
        - ./db.json:/data/db.json
      restart: "always"
      command: json-server --watch db.json